// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GenerateReport(arg1:main.GenerateReportPayload):Promise<string>;

export function GetAllSettings():Promise<Record<string, any>>;

export function GetSetting(arg1:string):Promise<any>;

export function ListOllamaModels(arg1:string):Promise<Array<string>>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenFileDialog(arg1:main.DialogOptions):Promise<string>;

export function OpenPath(arg1:string):Promise<void>;

export function ParseWithClaude(arg1:main.ParsePayload):Promise<Record<string, any>>;

export function ReadFile(arg1:string):Promise<main.FileInfo>;

export function RenderReport(arg1:main.GenerateReportPayload):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SetSetting(arg1:string,arg2:any):Promise<void>;

export function ShowSaveDialog(arg1:main.DialogOptions):Promise<string>;
